name: Node CI

on: [push, pull_request]

jobs:
  build-client:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node-version: [12.x, 13.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1.1.0
      - name: Build and Test Client
        run: |
          pushd client/src/test
          npm install
          npm run build --if-present
          npm run test --if-present
          popd

  build-server:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubunut-latest]
        node-version: [12.x, 13.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1.1.0
      - name: Build and Test Client
        run: |
          pushd server/src/test
          npm install
          npm run build --if-present
          npm run test --if-present
          popd
